//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sres.app.ServicioPIDE {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEBase", Namespace="http://schemas.datacontract.org/2004/07/EntidadPIDE.minem.gob.pe")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(sres.app.ServicioPIDE.BEDatosPrincipalesRUC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(sres.app.ServicioPIDE.BEDatosRepresenatesRUC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(sres.app.ServicioPIDE.BEDatosMigraciones))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(sres.app.ServicioPIDE.BEDatosSunarp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(sres.app.ServicioPIDE.BEDatosSUNEDU))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(sres.app.ServicioPIDE.BEDatosAntPNP))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(sres.app.ServicioPIDE.BEDatosAntPenales))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(sres.app.ServicioPIDE.BEDatosDNI))]
    public partial class BEBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OKField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrMsg {
            get {
                return this.ErrMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrMsgField, value) != true)) {
                    this.ErrMsgField = value;
                    this.RaisePropertyChanged("ErrMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OK {
            get {
                return this.OKField;
            }
            set {
                if ((this.OKField.Equals(value) != true)) {
                    this.OKField = value;
                    this.RaisePropertyChanged("OK");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEDatosPrincipalesRUC", Namespace="http://schemas.datacontract.org/2004/07/EntidadPIDE.minem.gob.pe")]
    [System.SerializableAttribute()]
    public partial class BEDatosPrincipalesRUC : sres.app.ServicioPIDE.BEBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIIUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodTipoViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodTipoZonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoDistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoDptoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoProvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomicilioLegalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaAltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaBajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HabidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCIIUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoZonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZonaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CIIU {
            get {
                return this.CIIUField;
            }
            set {
                if ((object.ReferenceEquals(this.CIIUField, value) != true)) {
                    this.CIIUField = value;
                    this.RaisePropertyChanged("CIIU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodTipoVia {
            get {
                return this.CodTipoViaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodTipoViaField, value) != true)) {
                    this.CodTipoViaField = value;
                    this.RaisePropertyChanged("CodTipoVia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodTipoZona {
            get {
                return this.CodTipoZonaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodTipoZonaField, value) != true)) {
                    this.CodTipoZonaField = value;
                    this.RaisePropertyChanged("CodTipoZona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoDist {
            get {
                return this.CodigoDistField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoDistField, value) != true)) {
                    this.CodigoDistField = value;
                    this.RaisePropertyChanged("CodigoDist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoDpto {
            get {
                return this.CodigoDptoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoDptoField, value) != true)) {
                    this.CodigoDptoField = value;
                    this.RaisePropertyChanged("CodigoDpto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoProv {
            get {
                return this.CodigoProvField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoProvField, value) != true)) {
                    this.CodigoProvField = value;
                    this.RaisePropertyChanged("CodigoProv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DomicilioLegal {
            get {
                return this.DomicilioLegalField;
            }
            set {
                if ((object.ReferenceEquals(this.DomicilioLegalField, value) != true)) {
                    this.DomicilioLegalField = value;
                    this.RaisePropertyChanged("DomicilioLegal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaAlta {
            get {
                return this.FechaAltaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaAltaField, value) != true)) {
                    this.FechaAltaField = value;
                    this.RaisePropertyChanged("FechaAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaBaja {
            get {
                return this.FechaBajaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaBajaField, value) != true)) {
                    this.FechaBajaField = value;
                    this.RaisePropertyChanged("FechaBaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Habido {
            get {
                return this.HabidoField;
            }
            set {
                if ((this.HabidoField.Equals(value) != true)) {
                    this.HabidoField = value;
                    this.RaisePropertyChanged("Habido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCIIU {
            get {
                return this.NombreCIIUField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCIIUField, value) != true)) {
                    this.NombreCIIUField = value;
                    this.RaisePropertyChanged("NombreCIIU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numeracion {
            get {
                return this.NumeracionField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeracionField, value) != true)) {
                    this.NumeracionField = value;
                    this.RaisePropertyChanged("Numeracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia {
            get {
                return this.ReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciaField, value) != true)) {
                    this.ReferenciaField = value;
                    this.RaisePropertyChanged("Referencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruc {
            get {
                return this.RucField;
            }
            set {
                if ((object.ReferenceEquals(this.RucField, value) != true)) {
                    this.RucField = value;
                    this.RaisePropertyChanged("Ruc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoEmpresa {
            get {
                return this.TipoEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEmpresaField, value) != true)) {
                    this.TipoEmpresaField = value;
                    this.RaisePropertyChanged("TipoEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPersona {
            get {
                return this.TipoPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPersonaField, value) != true)) {
                    this.TipoPersonaField = value;
                    this.RaisePropertyChanged("TipoPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoVia {
            get {
                return this.TipoViaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoViaField, value) != true)) {
                    this.TipoViaField = value;
                    this.RaisePropertyChanged("TipoVia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoZona {
            get {
                return this.TipoZonaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoZonaField, value) != true)) {
                    this.TipoZonaField = value;
                    this.RaisePropertyChanged("TipoZona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubigeo {
            get {
                return this.UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.UbigeoField, value) != true)) {
                    this.UbigeoField = value;
                    this.RaisePropertyChanged("Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Via {
            get {
                return this.ViaField;
            }
            set {
                if ((object.ReferenceEquals(this.ViaField, value) != true)) {
                    this.ViaField = value;
                    this.RaisePropertyChanged("Via");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zona {
            get {
                return this.ZonaField;
            }
            set {
                if ((object.ReferenceEquals(this.ZonaField, value) != true)) {
                    this.ZonaField = value;
                    this.RaisePropertyChanged("Zona");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEDatosRepresenatesRUC", Namespace="http://schemas.datacontract.org/2004/07/EntidadPIDE.minem.gob.pe")]
    [System.SerializableAttribute()]
    public partial class BEDatosRepresenatesRUC : sres.app.ServicioPIDE.BEBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_cargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_deparField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desc_docideField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string num_ord_suceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rso_cargooField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rso_docideField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rso_fecactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rso_fecnacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rso_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rso_nrodocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rso_numrucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rso_usernaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rso_vdesdeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_cargo {
            get {
                return this.cod_cargoField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_cargoField, value) != true)) {
                    this.cod_cargoField = value;
                    this.RaisePropertyChanged("cod_cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_depar {
            get {
                return this.cod_deparField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_deparField, value) != true)) {
                    this.cod_deparField = value;
                    this.RaisePropertyChanged("cod_depar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desc_docide {
            get {
                return this.desc_docideField;
            }
            set {
                if ((object.ReferenceEquals(this.desc_docideField, value) != true)) {
                    this.desc_docideField = value;
                    this.RaisePropertyChanged("desc_docide");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string num_ord_suce {
            get {
                return this.num_ord_suceField;
            }
            set {
                if ((object.ReferenceEquals(this.num_ord_suceField, value) != true)) {
                    this.num_ord_suceField = value;
                    this.RaisePropertyChanged("num_ord_suce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rso_cargoo {
            get {
                return this.rso_cargooField;
            }
            set {
                if ((object.ReferenceEquals(this.rso_cargooField, value) != true)) {
                    this.rso_cargooField = value;
                    this.RaisePropertyChanged("rso_cargoo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rso_docide {
            get {
                return this.rso_docideField;
            }
            set {
                if ((object.ReferenceEquals(this.rso_docideField, value) != true)) {
                    this.rso_docideField = value;
                    this.RaisePropertyChanged("rso_docide");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rso_fecact {
            get {
                return this.rso_fecactField;
            }
            set {
                if ((object.ReferenceEquals(this.rso_fecactField, value) != true)) {
                    this.rso_fecactField = value;
                    this.RaisePropertyChanged("rso_fecact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rso_fecnac {
            get {
                return this.rso_fecnacField;
            }
            set {
                if ((object.ReferenceEquals(this.rso_fecnacField, value) != true)) {
                    this.rso_fecnacField = value;
                    this.RaisePropertyChanged("rso_fecnac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rso_nombre {
            get {
                return this.rso_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.rso_nombreField, value) != true)) {
                    this.rso_nombreField = value;
                    this.RaisePropertyChanged("rso_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rso_nrodoc {
            get {
                return this.rso_nrodocField;
            }
            set {
                if ((object.ReferenceEquals(this.rso_nrodocField, value) != true)) {
                    this.rso_nrodocField = value;
                    this.RaisePropertyChanged("rso_nrodoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rso_numruc {
            get {
                return this.rso_numrucField;
            }
            set {
                if ((object.ReferenceEquals(this.rso_numrucField, value) != true)) {
                    this.rso_numrucField = value;
                    this.RaisePropertyChanged("rso_numruc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rso_userna {
            get {
                return this.rso_usernaField;
            }
            set {
                if ((object.ReferenceEquals(this.rso_usernaField, value) != true)) {
                    this.rso_usernaField = value;
                    this.RaisePropertyChanged("rso_userna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rso_vdesde {
            get {
                return this.rso_vdesdeField;
            }
            set {
                if ((object.ReferenceEquals(this.rso_vdesdeField, value) != true)) {
                    this.rso_vdesdeField = value;
                    this.RaisePropertyChanged("rso_vdesde");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEDatosMigraciones", Namespace="http://schemas.datacontract.org/2004/07/EntidadPIDE.minem.gob.pe")]
    [System.SerializableAttribute()]
    public partial class BEDatosMigraciones : sres.app.ServicioPIDE.BEBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalidadMigracionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CalidadMigraciones {
            get {
                return this.CalidadMigracionesField;
            }
            set {
                if ((object.ReferenceEquals(this.CalidadMigracionesField, value) != true)) {
                    this.CalidadMigracionesField = value;
                    this.RaisePropertyChanged("CalidadMigraciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaField, value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEDatosSunarp", Namespace="http://schemas.datacontract.org/2004/07/EntidadPIDE.minem.gob.pe")]
    [System.SerializableAttribute()]
    public partial class BEDatosSunarp : sres.app.ServicioPIDE.BEBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApePaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OficinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroPlacaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeMaterno {
            get {
                return this.ApeMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeMaternoField, value) != true)) {
                    this.ApeMaternoField = value;
                    this.RaisePropertyChanged("ApeMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApePaterno {
            get {
                return this.ApePaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApePaternoField, value) != true)) {
                    this.ApePaternoField = value;
                    this.RaisePropertyChanged("ApePaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Libro {
            get {
                return this.LibroField;
            }
            set {
                if ((object.ReferenceEquals(this.LibroField, value) != true)) {
                    this.LibroField = value;
                    this.RaisePropertyChanged("Libro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumDocumento {
            get {
                return this.NumDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumDocumentoField, value) != true)) {
                    this.NumDocumentoField = value;
                    this.RaisePropertyChanged("NumDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumPartida {
            get {
                return this.NumPartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumPartidaField, value) != true)) {
                    this.NumPartidaField = value;
                    this.RaisePropertyChanged("NumPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Oficina {
            get {
                return this.OficinaField;
            }
            set {
                if ((object.ReferenceEquals(this.OficinaField, value) != true)) {
                    this.OficinaField = value;
                    this.RaisePropertyChanged("Oficina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoRegistro {
            get {
                return this.TipoRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoRegistroField, value) != true)) {
                    this.TipoRegistroField = value;
                    this.RaisePropertyChanged("TipoRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zona {
            get {
                return this.ZonaField;
            }
            set {
                if ((object.ReferenceEquals(this.ZonaField, value) != true)) {
                    this.ZonaField = value;
                    this.RaisePropertyChanged("Zona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroPlaca {
            get {
                return this.numeroPlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroPlacaField, value) != true)) {
                    this.numeroPlacaField = value;
                    this.RaisePropertyChanged("numeroPlaca");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEDatosSUNEDU", Namespace="http://schemas.datacontract.org/2004/07/EntidadPIDE.minem.gob.pe")]
    [System.SerializableAttribute()]
    public partial class BEDatosSUNEDU : sres.app.ServicioPIDE.BEBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbreviaturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApePaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaConsultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraConsultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsjRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloProfesionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniversidadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Abreviatura {
            get {
                return this.AbreviaturaField;
            }
            set {
                if ((object.ReferenceEquals(this.AbreviaturaField, value) != true)) {
                    this.AbreviaturaField = value;
                    this.RaisePropertyChanged("Abreviatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeMaterno {
            get {
                return this.ApeMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeMaternoField, value) != true)) {
                    this.ApeMaternoField = value;
                    this.RaisePropertyChanged("ApeMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApePaterno {
            get {
                return this.ApePaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApePaternoField, value) != true)) {
                    this.ApePaternoField = value;
                    this.RaisePropertyChanged("ApePaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaConsulta {
            get {
                return this.FechaConsultaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaConsultaField, value) != true)) {
                    this.FechaConsultaField = value;
                    this.RaisePropertyChanged("FechaConsulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraConsulta {
            get {
                return this.HoraConsultaField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraConsultaField, value) != true)) {
                    this.HoraConsultaField = value;
                    this.RaisePropertyChanged("HoraConsulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsjRespuesta {
            get {
                return this.MsjRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.MsjRespuestaField, value) != true)) {
                    this.MsjRespuestaField = value;
                    this.RaisePropertyChanged("MsjRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumDocumento {
            get {
                return this.NumDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumDocumentoField, value) != true)) {
                    this.NumDocumentoField = value;
                    this.RaisePropertyChanged("NumDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaField, value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TituloProfesional {
            get {
                return this.TituloProfesionalField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloProfesionalField, value) != true)) {
                    this.TituloProfesionalField = value;
                    this.RaisePropertyChanged("TituloProfesional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Universidad {
            get {
                return this.UniversidadField;
            }
            set {
                if ((object.ReferenceEquals(this.UniversidadField, value) != true)) {
                    this.UniversidadField = value;
                    this.RaisePropertyChanged("Universidad");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEDatosAntPNP", Namespace="http://schemas.datacontract.org/2004/07/EntidadPIDE.minem.gob.pe")]
    [System.SerializableAttribute()]
    public partial class BEDatosAntPNP : sres.app.ServicioPIDE.BEBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string antecedenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contexturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dobleIdentidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string homonimiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lugarNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreMadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombrePadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombrecompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tallaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoDocumentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaField, value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string antecedente {
            get {
                return this.antecedenteField;
            }
            set {
                if ((object.ReferenceEquals(this.antecedenteField, value) != true)) {
                    this.antecedenteField = value;
                    this.RaisePropertyChanged("antecedente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoMaternoField, value) != true)) {
                    this.apellidoMaternoField = value;
                    this.RaisePropertyChanged("apellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoPaternoField, value) != true)) {
                    this.apellidoPaternoField = value;
                    this.RaisePropertyChanged("apellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoPersona {
            get {
                return this.codigoPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoPersonaField, value) != true)) {
                    this.codigoPersonaField = value;
                    this.RaisePropertyChanged("codigoPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contextura {
            get {
                return this.contexturaField;
            }
            set {
                if ((object.ReferenceEquals(this.contexturaField, value) != true)) {
                    this.contexturaField = value;
                    this.RaisePropertyChanged("contextura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dobleIdentidad {
            get {
                return this.dobleIdentidadField;
            }
            set {
                if ((object.ReferenceEquals(this.dobleIdentidadField, value) != true)) {
                    this.dobleIdentidadField = value;
                    this.RaisePropertyChanged("dobleIdentidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaNacimientoField, value) != true)) {
                    this.fechaNacimientoField = value;
                    this.RaisePropertyChanged("fechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string homonimia {
            get {
                return this.homonimiaField;
            }
            set {
                if ((object.ReferenceEquals(this.homonimiaField, value) != true)) {
                    this.homonimiaField = value;
                    this.RaisePropertyChanged("homonimia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lugarNacimiento {
            get {
                return this.lugarNacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.lugarNacimientoField, value) != true)) {
                    this.lugarNacimientoField = value;
                    this.RaisePropertyChanged("lugarNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreMadre {
            get {
                return this.nombreMadreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreMadreField, value) != true)) {
                    this.nombreMadreField = value;
                    this.RaisePropertyChanged("nombreMadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrePadre {
            get {
                return this.nombrePadreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombrePadreField, value) != true)) {
                    this.nombrePadreField = value;
                    this.RaisePropertyChanged("nombrePadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrecompleto {
            get {
                return this.nombrecompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.nombrecompletoField, value) != true)) {
                    this.nombrecompletoField = value;
                    this.RaisePropertyChanged("nombrecompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.nombresField, value) != true)) {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nroDocumento {
            get {
                return this.nroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.nroDocumentoField, value) != true)) {
                    this.nroDocumentoField = value;
                    this.RaisePropertyChanged("nroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string talla {
            get {
                return this.tallaField;
            }
            set {
                if ((object.ReferenceEquals(this.tallaField, value) != true)) {
                    this.tallaField = value;
                    this.RaisePropertyChanged("talla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoDocumentoField, value) != true)) {
                    this.tipoDocumentoField = value;
                    this.RaisePropertyChanged("tipoDocumento");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEDatosAntPenales", Namespace="http://schemas.datacontract.org/2004/07/EntidadPIDE.minem.gob.pe")]
    [System.SerializableAttribute()]
    public partial class BEDatosAntPenales : sres.app.ServicioPIDE.BEBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespuestaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaField, value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEDatosDNI", Namespace="http://schemas.datacontract.org/2004/07/EntidadPIDE.minem.gob.pe")]
    [System.SerializableAttribute()]
    public partial class BEDatosDNI : sres.app.ServicioPIDE.BEBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RestriccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbigeoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni {
            get {
                return this.DniField;
            }
            set {
                if ((object.ReferenceEquals(this.DniField, value) != true)) {
                    this.DniField = value;
                    this.RaisePropertyChanged("Dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoCivil {
            get {
                return this.EstadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoCivilField, value) != true)) {
                    this.EstadoCivilField = value;
                    this.RaisePropertyChanged("EstadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Restriccion {
            get {
                return this.RestriccionField;
            }
            set {
                if ((object.ReferenceEquals(this.RestriccionField, value) != true)) {
                    this.RestriccionField = value;
                    this.RaisePropertyChanged("Restriccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubigeo {
            get {
                return this.UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.UbigeoField, value) != true)) {
                    this.UbigeoField = value;
                    this.RaisePropertyChanged("Ubigeo");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioPIDE.IsrvConsultas")]
    public interface IsrvConsultas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/ConsultaDNI_PIDE", ReplyAction="http://tempuri.org/IsrvConsultas/ConsultaDNI_PIDEResponse")]
        sres.app.ServicioPIDE.BEDatosDNI ConsultaDNI_PIDE(string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/ConsultaDNI_PIDE", ReplyAction="http://tempuri.org/IsrvConsultas/ConsultaDNI_PIDEResponse")]
        System.Threading.Tasks.Task<sres.app.ServicioPIDE.BEDatosDNI> ConsultaDNI_PIDEAsync(string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/DatosRUC_SUNAT", ReplyAction="http://tempuri.org/IsrvConsultas/DatosRUC_SUNATResponse")]
        sres.app.ServicioPIDE.BEDatosPrincipalesRUC DatosRUC_SUNAT(string RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/DatosRUC_SUNAT", ReplyAction="http://tempuri.org/IsrvConsultas/DatosRUC_SUNATResponse")]
        System.Threading.Tasks.Task<sres.app.ServicioPIDE.BEDatosPrincipalesRUC> DatosRUC_SUNATAsync(string RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/ConsultaRUC_PIDE", ReplyAction="http://tempuri.org/IsrvConsultas/ConsultaRUC_PIDEResponse")]
        sres.app.ServicioPIDE.BEDatosPrincipalesRUC ConsultaRUC_PIDE(string RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/ConsultaRUC_PIDE", ReplyAction="http://tempuri.org/IsrvConsultas/ConsultaRUC_PIDEResponse")]
        System.Threading.Tasks.Task<sres.app.ServicioPIDE.BEDatosPrincipalesRUC> ConsultaRUC_PIDEAsync(string RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/ConsultaRUCRepresentante_PIDE", ReplyAction="http://tempuri.org/IsrvConsultas/ConsultaRUCRepresentante_PIDEResponse")]
        sres.app.ServicioPIDE.BEDatosRepresenatesRUC[] ConsultaRUCRepresentante_PIDE(string RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/ConsultaRUCRepresentante_PIDE", ReplyAction="http://tempuri.org/IsrvConsultas/ConsultaRUCRepresentante_PIDEResponse")]
        System.Threading.Tasks.Task<sres.app.ServicioPIDE.BEDatosRepresenatesRUC[]> ConsultaRUCRepresentante_PIDEAsync(string RUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/ConsultaMIGRACIONES_PIDE", ReplyAction="http://tempuri.org/IsrvConsultas/ConsultaMIGRACIONES_PIDEResponse")]
        sres.app.ServicioPIDE.BEDatosMigraciones ConsultaMIGRACIONES_PIDE(string NUMDOC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/ConsultaMIGRACIONES_PIDE", ReplyAction="http://tempuri.org/IsrvConsultas/ConsultaMIGRACIONES_PIDEResponse")]
        System.Threading.Tasks.Task<sres.app.ServicioPIDE.BEDatosMigraciones> ConsultaMIGRACIONES_PIDEAsync(string NUMDOC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/ConsultaSUNARP_PIDE", ReplyAction="http://tempuri.org/IsrvConsultas/ConsultaSUNARP_PIDEResponse")]
        sres.app.ServicioPIDE.BEDatosSunarp[] ConsultaSUNARP_PIDE(string Tipo, string DNI, string RazonSocial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/ConsultaSUNARP_PIDE", ReplyAction="http://tempuri.org/IsrvConsultas/ConsultaSUNARP_PIDEResponse")]
        System.Threading.Tasks.Task<sres.app.ServicioPIDE.BEDatosSunarp[]> ConsultaSUNARP_PIDEAsync(string Tipo, string DNI, string RazonSocial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/ConsultaSUNEDU_PIDE", ReplyAction="http://tempuri.org/IsrvConsultas/ConsultaSUNEDU_PIDEResponse")]
        sres.app.ServicioPIDE.BEDatosSUNEDU[] ConsultaSUNEDU_PIDE(string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/ConsultaSUNEDU_PIDE", ReplyAction="http://tempuri.org/IsrvConsultas/ConsultaSUNEDU_PIDEResponse")]
        System.Threading.Tasks.Task<sres.app.ServicioPIDE.BEDatosSUNEDU[]> ConsultaSUNEDU_PIDEAsync(string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/ConsultaAntecedenteJudicial_PIDE", ReplyAction="http://tempuri.org/IsrvConsultas/ConsultaAntecedenteJudicial_PIDEResponse")]
        string ConsultaAntecedenteJudicial_PIDE(string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/ConsultaAntecedenteJudicial_PIDE", ReplyAction="http://tempuri.org/IsrvConsultas/ConsultaAntecedenteJudicial_PIDEResponse")]
        System.Threading.Tasks.Task<string> ConsultaAntecedenteJudicial_PIDEAsync(string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/ConsultaAntecedentePolicial_PIDE", ReplyAction="http://tempuri.org/IsrvConsultas/ConsultaAntecedentePolicial_PIDEResponse")]
        sres.app.ServicioPIDE.BEDatosAntPNP ConsultaAntecedentePolicial_PIDE(string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/ConsultaAntecedentePolicial_PIDE", ReplyAction="http://tempuri.org/IsrvConsultas/ConsultaAntecedentePolicial_PIDEResponse")]
        System.Threading.Tasks.Task<sres.app.ServicioPIDE.BEDatosAntPNP> ConsultaAntecedentePolicial_PIDEAsync(string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/ConsultaAntecedentePenales_PIDE", ReplyAction="http://tempuri.org/IsrvConsultas/ConsultaAntecedentePenales_PIDEResponse")]
        sres.app.ServicioPIDE.BEDatosAntPenales ConsultaAntecedentePenales_PIDE(string DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvConsultas/ConsultaAntecedentePenales_PIDE", ReplyAction="http://tempuri.org/IsrvConsultas/ConsultaAntecedentePenales_PIDEResponse")]
        System.Threading.Tasks.Task<sres.app.ServicioPIDE.BEDatosAntPenales> ConsultaAntecedentePenales_PIDEAsync(string DNI);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvConsultasChannel : sres.app.ServicioPIDE.IsrvConsultas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvConsultasClient : System.ServiceModel.ClientBase<sres.app.ServicioPIDE.IsrvConsultas>, sres.app.ServicioPIDE.IsrvConsultas {
        
        public IsrvConsultasClient() {
        }
        
        public IsrvConsultasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvConsultasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvConsultasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvConsultasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public sres.app.ServicioPIDE.BEDatosDNI ConsultaDNI_PIDE(string DNI) {
            return base.Channel.ConsultaDNI_PIDE(DNI);
        }
        
        public System.Threading.Tasks.Task<sres.app.ServicioPIDE.BEDatosDNI> ConsultaDNI_PIDEAsync(string DNI) {
            return base.Channel.ConsultaDNI_PIDEAsync(DNI);
        }
        
        public sres.app.ServicioPIDE.BEDatosPrincipalesRUC DatosRUC_SUNAT(string RUC) {
            return base.Channel.DatosRUC_SUNAT(RUC);
        }
        
        public System.Threading.Tasks.Task<sres.app.ServicioPIDE.BEDatosPrincipalesRUC> DatosRUC_SUNATAsync(string RUC) {
            return base.Channel.DatosRUC_SUNATAsync(RUC);
        }
        
        public sres.app.ServicioPIDE.BEDatosPrincipalesRUC ConsultaRUC_PIDE(string RUC) {
            return base.Channel.ConsultaRUC_PIDE(RUC);
        }
        
        public System.Threading.Tasks.Task<sres.app.ServicioPIDE.BEDatosPrincipalesRUC> ConsultaRUC_PIDEAsync(string RUC) {
            return base.Channel.ConsultaRUC_PIDEAsync(RUC);
        }
        
        public sres.app.ServicioPIDE.BEDatosRepresenatesRUC[] ConsultaRUCRepresentante_PIDE(string RUC) {
            return base.Channel.ConsultaRUCRepresentante_PIDE(RUC);
        }
        
        public System.Threading.Tasks.Task<sres.app.ServicioPIDE.BEDatosRepresenatesRUC[]> ConsultaRUCRepresentante_PIDEAsync(string RUC) {
            return base.Channel.ConsultaRUCRepresentante_PIDEAsync(RUC);
        }
        
        public sres.app.ServicioPIDE.BEDatosMigraciones ConsultaMIGRACIONES_PIDE(string NUMDOC) {
            return base.Channel.ConsultaMIGRACIONES_PIDE(NUMDOC);
        }
        
        public System.Threading.Tasks.Task<sres.app.ServicioPIDE.BEDatosMigraciones> ConsultaMIGRACIONES_PIDEAsync(string NUMDOC) {
            return base.Channel.ConsultaMIGRACIONES_PIDEAsync(NUMDOC);
        }
        
        public sres.app.ServicioPIDE.BEDatosSunarp[] ConsultaSUNARP_PIDE(string Tipo, string DNI, string RazonSocial) {
            return base.Channel.ConsultaSUNARP_PIDE(Tipo, DNI, RazonSocial);
        }
        
        public System.Threading.Tasks.Task<sres.app.ServicioPIDE.BEDatosSunarp[]> ConsultaSUNARP_PIDEAsync(string Tipo, string DNI, string RazonSocial) {
            return base.Channel.ConsultaSUNARP_PIDEAsync(Tipo, DNI, RazonSocial);
        }
        
        public sres.app.ServicioPIDE.BEDatosSUNEDU[] ConsultaSUNEDU_PIDE(string DNI) {
            return base.Channel.ConsultaSUNEDU_PIDE(DNI);
        }
        
        public System.Threading.Tasks.Task<sres.app.ServicioPIDE.BEDatosSUNEDU[]> ConsultaSUNEDU_PIDEAsync(string DNI) {
            return base.Channel.ConsultaSUNEDU_PIDEAsync(DNI);
        }
        
        public string ConsultaAntecedenteJudicial_PIDE(string DNI) {
            return base.Channel.ConsultaAntecedenteJudicial_PIDE(DNI);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaAntecedenteJudicial_PIDEAsync(string DNI) {
            return base.Channel.ConsultaAntecedenteJudicial_PIDEAsync(DNI);
        }
        
        public sres.app.ServicioPIDE.BEDatosAntPNP ConsultaAntecedentePolicial_PIDE(string DNI) {
            return base.Channel.ConsultaAntecedentePolicial_PIDE(DNI);
        }
        
        public System.Threading.Tasks.Task<sres.app.ServicioPIDE.BEDatosAntPNP> ConsultaAntecedentePolicial_PIDEAsync(string DNI) {
            return base.Channel.ConsultaAntecedentePolicial_PIDEAsync(DNI);
        }
        
        public sres.app.ServicioPIDE.BEDatosAntPenales ConsultaAntecedentePenales_PIDE(string DNI) {
            return base.Channel.ConsultaAntecedentePenales_PIDE(DNI);
        }
        
        public System.Threading.Tasks.Task<sres.app.ServicioPIDE.BEDatosAntPenales> ConsultaAntecedentePenales_PIDEAsync(string DNI) {
            return base.Channel.ConsultaAntecedentePenales_PIDEAsync(DNI);
        }
    }
}
