--------------------------------------------------------
-- Archivo creado  - martes-julio-21-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package Body PKG_SRES_CRITERIO
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "SRES"."PKG_SRES_CRITERIO" AS
  -- CONVOCATORIA
  PROCEDURE USP_SEL_BUSQ_CONVOCATORIA(
    PI_NRO_INFORME VARCHAR2,
    PI_NOMBRE VARCHAR2,
    PI_FECHA_INICIO DATE,
    PI_FECHA_FIN DATE,
    PI_REGISTROS NUMBER,
    PI_PAGINA NUMBER,
    PI_COLUMNA VARCHAR2,
    PI_ORDEN VARCHAR2,
    PO_REF OUT SYS_REFCURSOR
  ) AS    
    vTOTAL_REG INTEGER;
    vPAGINA_TOTAL INTEGER;
    vPAGINA_ACTUAL INTEGER := PI_PAGINA;
    vPAGINA_INICIAL INTEGER := 0;
    vQUERY_CONT VARCHAR2(10000) := '';
    vQUERY_SELECT VARCHAR2(10000) := '';
    vCOLUMNA VARCHAR2(200);
  BEGIN
    vQUERY_CONT := 'SELECT  COUNT(1)
                    FROM T_GENM_CONVOCATORIA C INNER JOIN
                    T_MAE_ETAPA E ON C.ID_ETAPA = E.ID_ETAPA
                    WHERE ' ||
                    CASE
                      WHEN PI_NRO_INFORME IS NOT NULL THEN
                      'LOWER(TRANSLATE(C.NRO_INFORME,''ÁÉÍÓÚáéíóú'',''AEIOUaeiou'')) like ''%''|| LOWER(TRANSLATE('''|| PI_NRO_INFORME ||''',''ÁÉÍÓÚáéíóú'',''AEIOUaeiou'')) ||''%'' AND '
                    END ||
                    'LOWER(TRANSLATE(C.NOMBRE,''ÁÉÍÓÚáéíóú'',''AEIOUaeiou'')) like ''%''|| LOWER(TRANSLATE('''|| PI_NOMBRE ||''',''ÁÉÍÓÚáéíóú'',''AEIOUaeiou'')) ||''%'' AND ' ||
                    CASE
                      WHEN PI_FECHA_INICIO IS NOT NULL AND PI_FECHA_FIN IS NOT NULL THEN
                      '(
                      TO_DATE(C.FECHA_INICIO) BETWEEN TO_DATE(''' || TO_CHAR(PI_FECHA_INICIO, 'DD/MM/YYYY') || ''') AND TO_DATE(''' || TO_CHAR(PI_FECHA_FIN, 'DD/MM/YYYY') || ''') OR
                      TO_DATE(C.FECHA_FIN) BETWEEN TO_DATE(''' || TO_CHAR(PI_FECHA_INICIO, 'DD/MM/YYYY') || ''') AND TO_DATE(''' || TO_CHAR(PI_FECHA_FIN, 'DD/MM/YYYY') || ''')
                      ) AND '
                      WHEN PI_FECHA_INICIO IS NOT NULL AND PI_FECHA_FIN IS NULL THEN
                      '(TO_DATE(C.FECHA_INICIO) >= TO_DATE(''' || TO_CHAR(PI_FECHA_INICIO, 'DD/MM/YYYY') || ''') OR TO_DATE(C.FECHA_FIN) >= TO_DATE(''' || TO_CHAR(PI_FECHA_INICIO, 'DD/MM/YYYY') || ''')) AND '
                      WHEN PI_FECHA_INICIO IS NULL AND PI_FECHA_FIN IS NOT NULL THEN
                      '(TO_DATE(C.FECHA_INICIO) <= TO_DATE(''' || TO_CHAR(PI_FECHA_FIN, 'DD/MM/YYYY') || ''') OR TO_DATE(C.FECHA_FIN) <= TO_DATE(''' || TO_CHAR(PI_FECHA_FIN, 'DD/MM/YYYY') || ''')) AND '
                    END ||
                    'C.FLAG_ESTADO = ''1''';
    EXECUTE IMMEDIATE vQUERY_CONT INTO vTOTAL_REG;
    
    vPAGINA_TOTAL := CEIL(TO_NUMBER(vTOTAL_REG) / TO_NUMBER(PI_REGISTROS));
    IF vPAGINA_ACTUAL = 0 THEN
      vPAGINA_ACTUAL := 1;
    END IF;
    IF vPAGINA_ACTUAL > vPAGINA_TOTAL THEN
      vPAGINA_ACTUAL := vPAGINA_TOTAL;
    END IF;

    vPAGINA_INICIAL := vPAGINA_ACTUAL - 1;
    
    vCOLUMNA := 'C.' || PI_COLUMNA;
    
    vQUERY_SELECT := 'SELECT * FROM 
                        (
                          SELECT  C.ID_CONVOCATORIA,
                                  C.NOMBRE,
                                  C.FECHA_INICIO,
                                  C.FECHA_FIN,
                                  C.LIMITE_POSTULANTE,
                                  C.NRO_INFORME,
                                  C.ID_ETAPA,
                                  E.NOMBRE AS "NOMBRE_ETAPA",
                                  C.FLAG_ESTADO,
                                  ROW_NUMBER() OVER (ORDER BY ' || vCOLUMNA || ' ' || PI_ORDEN ||') AS ROWNUMBER,'
                                  || vPAGINA_TOTAL || ' AS TOTAL_PAGINAS,'
                                  || vPAGINA_ACTUAL || ' AS PAGINA,'
                                  || PI_REGISTROS || ' AS CANTIDAD_REGISTROS,'
                                  || vTOTAL_REG || ' AS TOTAL_REGISTROS
                          FROM T_GENM_CONVOCATORIA C INNER JOIN
                          T_MAE_ETAPA E ON C.ID_ETAPA = E.ID_ETAPA
                          WHERE ' ||
                          CASE
                            WHEN PI_NRO_INFORME IS NOT NULL THEN
                            'LOWER(TRANSLATE(C.NRO_INFORME,''ÁÉÍÓÚáéíóú'',''AEIOUaeiou'')) like ''%''|| LOWER(TRANSLATE('''|| PI_NRO_INFORME ||''',''ÁÉÍÓÚáéíóú'',''AEIOUaeiou'')) ||''%'' AND '
                          END ||
                          'LOWER(TRANSLATE(C.NOMBRE,''ÁÉÍÓÚáéíóú'',''AEIOUaeiou'')) like ''%''|| LOWER(TRANSLATE('''|| PI_NOMBRE ||''',''ÁÉÍÓÚáéíóú'',''AEIOUaeiou'')) ||''%'' AND ' ||
                          CASE
                            WHEN PI_FECHA_INICIO IS NOT NULL AND PI_FECHA_FIN IS NOT NULL THEN
                            '(
                            TO_DATE(C.FECHA_INICIO) BETWEEN TO_DATE(''' || TO_CHAR(PI_FECHA_INICIO, 'DD/MM/YYYY') || ''') AND TO_DATE(''' || TO_CHAR(PI_FECHA_FIN, 'DD/MM/YYYY') || ''') OR
                            TO_DATE(C.FECHA_FIN) BETWEEN TO_DATE(''' || TO_CHAR(PI_FECHA_INICIO, 'DD/MM/YYYY') || ''') AND TO_DATE(''' || TO_CHAR(PI_FECHA_FIN, 'DD/MM/YYYY') || ''')
                            ) AND '
                            WHEN PI_FECHA_INICIO IS NOT NULL AND PI_FECHA_FIN IS NULL THEN
                            '(TO_DATE(C.FECHA_INICIO) >= TO_DATE(''' || TO_CHAR(PI_FECHA_INICIO, 'DD/MM/YYYY') || ''') OR TO_DATE(C.FECHA_FIN) >= TO_DATE(''' || TO_CHAR(PI_FECHA_INICIO, 'DD/MM/YYYY') || ''')) AND '
                            WHEN PI_FECHA_INICIO IS NULL AND PI_FECHA_FIN IS NOT NULL THEN
                            '(TO_DATE(C.FECHA_INICIO) <= TO_DATE(''' || TO_CHAR(PI_FECHA_FIN, 'DD/MM/YYYY') || ''') OR TO_DATE(C.FECHA_FIN) <= TO_DATE(''' || TO_CHAR(PI_FECHA_FIN, 'DD/MM/YYYY') || ''')) AND '
                          END ||
                          'C.FLAG_ESTADO = ''1''
                        )
                    WHERE  ROWNUMBER BETWEEN ' || TO_CHAR(PI_REGISTROS * vPAGINA_INICIAL + 1) || ' AND ' || TO_CHAR(PI_REGISTROS * (vPAGINA_INICIAL + 1));
    
    OPEN PO_REF FOR vQUERY_SELECT;
  END USP_SEL_BUSQ_CONVOCATORIA;
  
  PROCEDURE USP_SEL_OBTIENE_CONVOCATORIA(
    PI_ID_CONVOCATORIA NUMBER,
    PO_REF OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN PO_REF FOR
    SELECT
    C.ID_CONVOCATORIA,
    C.NOMBRE,
    C.FECHA_INICIO,
    C.FECHA_FIN,
    C.LIMITE_POSTULANTE,
    C.NRO_INFORME,
    C.FLAG_ESTADO
    FROM T_GENM_CONVOCATORIA C
    WHERE C.ID_CONVOCATORIA = PI_ID_CONVOCATORIA;
  END USP_SEL_OBTIENE_CONVOCATORIA;
  
  -- INSCRIPCION
  PROCEDURE USP_MAN_GUARDA_INSCRIPCION(
    PI_ID_INSCRIPCION IN OUT NUMBER,
    PI_ID_CONVOCATORIA NUMBER,
    PI_ID_INSTITUCION NUMBER,
    PI_UPD_USUARIO NUMBER,
    PO_ROWAFFECTED OUT NUMBER
  ) AS
    vID NUMBER;
  BEGIN
    
    SELECT MAX(ID_INSCRIPCION) INTO vID
    FROM T_GENM_INSCRIPCION
    WHERE ID_INSCRIPCION = PI_ID_INSCRIPCION;
    
    IF vID IS NULL THEN
      PI_ID_INSCRIPCION := SQ_GENM_INSCRIPCION.NEXTVAL();
      
      INSERT INTO T_GENM_INSCRIPCION
      (ID_INSCRIPCION, ID_CONVOCATORIA, ID_INSTITUCION, REG_USUARIO)
      VALUES
      (PI_ID_INSCRIPCION, PI_ID_CONVOCATORIA, PI_ID_INSTITUCION, PI_UPD_USUARIO);
    ELSE
      UPDATE T_GENM_INSCRIPCION I SET
      I.UPD_USUARIO = PI_UPD_USUARIO,
      I.UPD_FECHA = SYSDATE
      WHERE
      I.ID_INSCRIPCION = PI_ID_INSCRIPCION;
    END IF;
    
    PO_ROWAFFECTED := SQL%ROWCOUNT;
  END USP_MAN_GUARDA_INSCRIPCION;
  
  PROCEDURE USP_SEL_OBTIENE_INSC_CONV_INST(
    PI_ID_CONVOCATORIA NUMBER,
    PI_ID_INSTITUCION NUMBER,
    PO_REF OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN PO_REF FOR
    SELECT
    I.ID_INSCRIPCION,
    I.ID_CONVOCATORIA,
    I.ID_INSTITUCION,
    I.FLAG_ANULAR,
    I.NRO_INFORME_PRELIMINAR,
    I.FLAG_ESTADO
    FROM T_GENM_INSCRIPCION I
    WHERE I.ID_CONVOCATORIA = PI_ID_CONVOCATORIA
    AND I.ID_INSTITUCION = PI_ID_INSTITUCION;
  END USP_SEL_OBTIENE_INSC_CONV_INST;
  
  -- REQUERIMIENTO
  PROCEDURE USP_SEL_LISTA_INSCRQ_CONV_INSC(
    PI_ID_CONVOCATORIA NUMBER,
    PI_ID_INSCRIPCION NUMBER,
    PO_REF OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN PO_REF FOR
    SELECT
    R.ID_REQUERIMIENTO,
    R.NOMBRE AS "NOMBRE_REQUERIMIENTO",
    R.FLAG_ESTADO AS "FLAG_ESTADO_REQUERIMIENTO",
    IR.ARCHIVO_BASE,
    IR.ARCHIVO_CIFRADO,
    IR.VALIDO AS "VALIDO",
    IR.OBSERVACION,
    I.ID_INSTITUCION
    FROM T_GENM_REQUERIMIENTO R INNER JOIN
    T_GEND_CONVOCATORIA_REQUERIM CR ON R.ID_REQUERIMIENTO = CR.ID_REQUERIMIENTO AND R.FLAG_ESTADO = '1' LEFT JOIN
    T_GEND_INSCRIPCION_REQUERIR IR ON CR.ID_CONVOCATORIA = IR.ID_CONVOCATORIA AND CR.ID_REQUERIMIENTO = IR.ID_REQUERIMIENTO AND IR.ID_INSCRIPCION = PI_ID_INSCRIPCION LEFT JOIN
    T_GENM_INSCRIPCION I ON IR.ID_INSCRIPCION = I.ID_INSCRIPCION
    WHERE CR.ID_CONVOCATORIA = PI_ID_CONVOCATORIA
    AND CR.FLAG_ESTADO = '1';
  END USP_SEL_LISTA_INSCRQ_CONV_INSC;
  
  PROCEDURE USP_SEL_OBTIENE_INSCRQ(
    PI_ID_CONVOCATORIA NUMBER,
    PI_ID_INSCRIPCION NUMBER,
    PI_ID_REQUERIMIENTO NUMBER,
    PO_REF OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN PO_REF FOR
    SELECT
    IR.ID_CONVOCATORIA,
    IR.ID_INSCRIPCION,
    IR.ID_REQUERIMIENTO,
    IR.ARCHIVO_BASE,
    IR.ARCHIVO_CIFRADO,
    IR.VALIDO AS "VALIDO",
    IR.OBSERVACION
    FROM T_GEND_INSCRIPCION_REQUERIR IR
    WHERE
    IR.ID_CONVOCATORIA = PI_ID_CONVOCATORIA AND
    IR.ID_INSCRIPCION = PI_ID_INSCRIPCION AND
    IR.ID_REQUERIMIENTO = PI_ID_REQUERIMIENTO;
  END USP_SEL_OBTIENE_INSCRQ;
  
  PROCEDURE USP_MAN_GUARDA_INSCRQ(
    PI_ID_CONVOCATORIA NUMBER,
    PI_ID_INSCRIPCION NUMBER,
    PI_ID_REQUERIMIENTO NUMBER,
    PI_ARCHIVO_BASE VARCHAR2,
    PI_ARCHIVO_CIFRADO VARCHAR2,
    PI_UPD_USUARIO NUMBER,
    PO_ROWAFFECTED OUT NUMBER
  ) AS
  vRegistros NUMBER;
  BEGIN
    SELECT COUNT(1) INTO vRegistros
    FROM T_GEND_INSCRIPCION_REQUERIR IR
    WHERE
    IR.ID_CONVOCATORIA = PI_ID_CONVOCATORIA AND
    IR.ID_INSCRIPCION = PI_ID_INSCRIPCION AND
    IR.ID_REQUERIMIENTO = PI_ID_REQUERIMIENTO;
    
    IF vRegistros = 0 THEN
      INSERT INTO T_GEND_INSCRIPCION_REQUERIR
      (ID_CONVOCATORIA, ID_INSCRIPCION, ID_REQUERIMIENTO, ARCHIVO_BASE, ARCHIVO_CIFRADO, REG_USUARIO)
      VALUES
      (PI_ID_CONVOCATORIA, PI_ID_INSCRIPCION, PI_ID_REQUERIMIENTO, PI_ARCHIVO_BASE, PI_ARCHIVO_CIFRADO, PI_UPD_USUARIO);
    ELSE
      UPDATE T_GEND_INSCRIPCION_REQUERIR IR SET
      IR.ARCHIVO_BASE = PI_ARCHIVO_BASE,
      IR.ARCHIVO_CIFRADO = PI_ARCHIVO_CIFRADO,
      IR.UPD_FECHA = SYSDATE,
      IR.UPD_USUARIO = PI_UPD_USUARIO
      WHERE
      IR.ID_CONVOCATORIA = PI_ID_CONVOCATORIA AND
      IR.ID_INSCRIPCION = PI_ID_INSCRIPCION AND
      IR.ID_REQUERIMIENTO = PI_ID_REQUERIMIENTO;
    END IF;
    
    PO_ROWAFFECTED := SQL%ROWCOUNT;
  END USP_MAN_GUARDA_INSCRQ;
  
  PROCEDURE USP_SEL_LISTA_CRI_CONV(
    PI_ID_CONVOCATORIA NUMBER,
    PO_REF OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN PO_REF FOR
    SELECT
    C.ID_CRITERIO,
    C.NOMBRE,
    C.FLAG_ESTADO
    FROM T_GEND_CONVOCATORIA_CRITERIO CR INNER JOIN
    T_GENM_CRITERIO C ON CR.ID_CRITERIO = C.ID_CRITERIO AND CR.FLAG_ESTADO = C.FLAG_ESTADO
    WHERE
    CR.ID_CONVOCATORIA = PI_ID_CONVOCATORIA AND
    CR.FLAG_ESTADO = '1';
  END USP_SEL_LISTA_CRI_CONV;
  
  PROCEDURE USP_SEL_OBTIENE_CRI_CONV(
    PI_ID_CONVOCATORIA NUMBER,
    PI_ID_CRITERIO NUMBER,
    PO_REF OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN PO_REF FOR
    SELECT
    C.ID_CRITERIO,
    C.NOMBRE,
    C.FLAG_ESTADO
    FROM T_GEND_CONVOCATORIA_CRITERIO CR INNER JOIN
    T_GENM_CRITERIO C ON CR.ID_CRITERIO = C.ID_CRITERIO AND CR.FLAG_ESTADO = C.FLAG_ESTADO
    WHERE
    CR.ID_CONVOCATORIA = PI_ID_CONVOCATORIA AND
    CR.ID_CRITERIO = PI_ID_CRITERIO AND
    CR.FLAG_ESTADO = '1';
  END USP_SEL_OBTIENE_CRI_CONV;
  
  PROCEDURE USP_INS_REGISTRA_INSCTRAZA(
    PI_ID_INSCRIPCION NUMBER,
    PI_DESCRIPCION VARCHAR2,
    PI_UPD_USUARIO NUMBER,
    PO_ROWAFFECTED OUT NUMBER
  ) AS
    vID NUMBER;
  BEGIN
    vID := SQ_GEND_INSCRIPCION_TRAZA.NEXTVAL();
    
    INSERT INTO T_GEND_INSCRIPCION_TRAZA
    (ID_INSCRIPCION, ID_TRAZABILIDAD, DESCRIPCION, REG_USUARIO)
    VALUES
    (PI_ID_INSCRIPCION, vID, PI_DESCRIPCION, PI_UPD_USUARIO);
    
    PO_ROWAFFECTED := SQL%ROWCOUNT;
  END USP_INS_REGISTRA_INSCTRAZA;
  
  PROCEDURE USP_SEL_LISTA_CASO_CRITERIO( --ACTUALIZADO 17-07-20
    PI_ID_CRITERIO NUMBER,
    PI_ID_CONVOCATORIA NUMBER, --ADD
    PO_REF OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN PO_REF FOR
    SELECT
    C.ID_CASO,
    C.NOMBRE,
    C.ID_CRITERIO,
    C.FLAG_ESTADO
    FROM  T_GEND_CONV_CRI_CASO CCC LEFT JOIN 
    T_GENM_CASO C ON CCC.ID_CASO = C.ID_CASO AND CCC.ID_CRITERIO = C.ID_CRITERIO
    WHERE CCC.ID_CRITERIO = PI_ID_CRITERIO AND CCC.ID_CONVOCATORIA = PI_ID_CONVOCATORIA AND CCC.FLAG_ESTADO = '1'
    ORDER BY CCC.ID_CASO ASC;
  END USP_SEL_LISTA_CASO_CRITERIO;
  
  PROCEDURE USP_SEL_LISTA_COMPONENTE_CASO(
    PI_ID_CASO NUMBER,
    PO_REF OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN PO_REF FOR
    SELECT
    C.ID_COMPONENTE,
    C.NOMBRE,
    C.INCREMENTABLE,
    C.ID_CASO,
    C.ID_CRITERIO,
    C.FLAG_ESTADO
    FROM T_GENM_COMPONENTE C
    WHERE C.ID_CASO = PI_ID_CASO;
  END USP_SEL_LISTA_COMPONENTE_CASO;
  
  PROCEDURE USP_DEL_INDICADOR_DATA(
        PI_ID_CRITERIO IN NUMBER,
        PI_ID_CASO  IN NUMBER,
        PI_ID_COMPONENTE IN NUMBER,
        PI_ID_INSCRIPCION IN NUMBER,
        PI_ELIMINAR_INDICADOR IN VARCHAR2
  )IS
        vSql            VARCHAR2(250);
  BEGIN
        vSql := 'UPDATE T_MAEM_INDICADOR_DATA SET FLAG_ESTADO = ''0'' WHERE ID_CRITERIO ='||PI_ID_CRITERIO||' AND ID_CASO = '||PI_ID_CASO||' AND ID_COMPONENTE = '||PI_ID_COMPONENTE||' AND ID_INSCRIPCION = '||PI_ID_INSCRIPCION||' AND ID_INDICADOR IN ('||PI_ELIMINAR_INDICADOR||')';
        EXECUTE IMMEDIATE vSql;
  END USP_DEL_INDICADOR_DATA;
  
  PROCEDURE USP_SEL_INDICADORDATA_ID(
    PI_ID_CRITERIO NUMBER,
    PI_ID_CASO NUMBER,
    PI_ID_COMPONENTE NUMBER,
    PI_ID_INSCRIPCION NUMBER,
    PO_REF OUT SYS_REFCURSOR
  )AS
  BEGIN
    OPEN PO_REF FOR
    SELECT  DISTINCT ID_CRITERIO, ID_CASO, ID_COMPONENTE, ID_INDICADOR
    FROM    T_MAEM_INDICADOR_DATA
    WHERE   ID_CRITERIO = PI_ID_CRITERIO AND ID_CASO = PI_ID_CASO AND ID_COMPONENTE = PI_ID_COMPONENTE AND FLAG_ESTADO = '1'            
    ORDER BY ID_INDICADOR ASC;
  END USP_SEL_INDICADORDATA_ID;
  
  PROCEDURE USP_SEL_FORM_PARAM_DET(
    PI_ID_PARAMETRO NUMBER,
    PO_REF OUT SYS_REFCURSOR
  )AS
  BEGIN
      OPEN PO_REF FOR
      SELECT  *
      FROM    T_MAED_PARAMETRO
      WHERE ID_PARAMETRO = PI_ID_PARAMETRO AND FLAG_ESTADO = '1';
  END USP_SEL_FORM_PARAM_DET;
  
  PROCEDURE USP_SEL_DATA_PARAM_DET(
    PI_ID_PARAMETRO NUMBER,
    PO_REF OUT SYS_REFCURSOR
  )AS
  BEGIN
      OPEN PO_REF FOR
      SELECT  *
      FROM    T_MAED_PARAMETRO
      WHERE ID_PARAMETRO = PI_ID_PARAMETRO AND FLAG_ESTADO = '1';
  END USP_SEL_DATA_PARAM_DET;
  
  PROCEDURE USP_SEL_CONV_CRI_CASO_DOC(
    PI_ID_CRITERIO NUMBER,
    PI_ID_CASO NUMBER,
    PI_ID_CONVOCATORIA NUMBER,
    PO_REF OUT SYS_REFCURSOR
  )AS
  BEGIN
      OPEN PO_REF FOR
      SELECT
      D.ID_DOCUMENTO,
      D.ID_CRITERIO,
      D.NOMBRE,
      D.DESCRIPCION,
      CCCD.ID_CONVOCATORIA,
      CCCD.ID_CASO
      FROM    T_GEND_CONV_CRI_CASO_DOC CCCD LEFT JOIN
      T_GENM_DOCUMENTO D ON CCCD.ID_DOCUMENTO = D.ID_DOCUMENTO AND CCCD.ID_CRITERIO = D.ID_CRITERIO
      WHERE CCCD.ID_CONVOCATORIA = PI_ID_CONVOCATORIA AND CCCD.ID_CRITERIO = PI_ID_CRITERIO AND CCCD.ID_CASO = PI_ID_CASO AND CCCD.FLAG_ESTADO = '1';
  END USP_SEL_CONV_CRI_CASO_DOC;
  
  PROCEDURE USP_SEL_GET_FORMULA_PARAM(
    PI_ID_CRITERIO NUMBER,
    PI_ID_CASO NUMBER,
    PI_ID_COMPONENTE NUMBER,
    PI_ID_PARAMETRO NUMBER,
    PO_REF OUT SYS_REFCURSOR
  )AS
  BEGIN
    OPEN PO_REF FOR
    SELECT  *
    FROM    T_MAEM_FORMULA_PARAMETRO
    WHERE   ID_CRITERIO = PI_ID_CRITERIO AND ID_CASO = PI_ID_CASO AND ID_COMPONENTE = PI_ID_COMPONENTE AND ID_PARAMETRO = PI_ID_PARAMETRO;
  END USP_SEL_GET_FORMULA_PARAM;
  
  PROCEDURE USP_SEL_GET_PARAM_DET_REL(
    PI_ID_PARAMETRO NUMBER,
    PI_PARAMETROS VARCHAR2,
    PI_DETALLES VARCHAR2,
    PO_REF OUT SYS_REFCURSOR
  )AS
  BEGIN
    OPEN PO_REF FOR
    SELECT  
    PD.ID_DETALLE,
    PD.NOMBRE,
    PD.ID_PARAMETRO
    FROM    T_MAED_PARAMETRO_RELACION PDR LEFT JOIN
    T_MAED_PARAMETRO PD ON PDR.ID_PARAMETRO = PD.ID_PARAMETRO AND PDR.ID_DETALLE = PD.ID_DETALLE
    WHERE PDR.ID_PARAMETRO = PI_ID_PARAMETRO AND PDR.PARAMETROS = PI_PARAMETROS AND PDR.DETALLES = PI_DETALLES AND PDR.FLAG_ESTADO = '1';
  END USP_SEL_GET_PARAM_DET_REL;
  
  PROCEDURE USP_PRC_MAN_DOCUMENTO_DATA(
    PI_ID_CONVOCATORIA NUMBER,
    PI_ID_CRITERIO NUMBER,
    PI_ID_CASO NUMBER,
    PI_ID_DOCUMENTO NUMBER,
    PI_ID_INSCRIPCION NUMBER,
    PI_ARCHIVO_BASE VARCHAR2,
    PI_ARCHIVO_TIPO VARCHAR2,
    PI_USUARIO_GUARDAR NUMBER,
    PO_ROWAFFECTED OUT NUMBER
  )IS
        vCONT NUMBER;
  BEGIN
    SELECT COUNT(*) INTO vCONT 
    FROM T_GEND_CONV_CRI_CASO_DOC_INSC
    WHERE ID_CRITERIO = PI_ID_CRITERIO 
          AND ID_CASO = PI_ID_CASO
          AND ID_CONVOCATORIA = PI_ID_CONVOCATORIA
          AND ID_DOCUMENTO = PI_ID_DOCUMENTO
          AND ID_INSCRIPCION = PI_ID_INSCRIPCION;
          
    IF vCONT = 0 THEN 
      INSERT INTO T_GEND_CONV_CRI_CASO_DOC_INSC (ID_CONVOCATORIA, ID_CRITERIO, ID_CASO, ID_DOCUMENTO, ID_INSCRIPCION, ARCHIVO_BASE, ARCHIVO_TIPO, REG_USUARIO, REG_FECHA)
      VALUES (PI_ID_CONVOCATORIA, PI_ID_CRITERIO, PI_ID_CASO, PI_ID_DOCUMENTO, PI_ID_INSCRIPCION, PI_ARCHIVO_BASE, PI_ARCHIVO_TIPO, PI_USUARIO_GUARDAR, SYSDATE);
    ELSE
      UPDATE T_GEND_CONV_CRI_CASO_DOC_INSC
      SET    ARCHIVO_BASE = PI_ARCHIVO_BASE,
             ARCHIVO_TIPO = PI_ARCHIVO_TIPO,
             UPD_USUARIO = PI_USUARIO_GUARDAR,
             UPD_FECHA = SYSDATE
      WHERE  ID_CRITERIO = PI_ID_CRITERIO 
             AND ID_CASO = PI_ID_CASO
             AND ID_CONVOCATORIA = PI_ID_CONVOCATORIA
             AND ID_DOCUMENTO = PI_ID_DOCUMENTO
             AND ID_INSCRIPCION = PI_ID_INSCRIPCION;
    END IF;
    PO_ROWAFFECTED := SQL%ROWCOUNT;      
  END USP_PRC_MAN_DOCUMENTO_DATA;
  
  PROCEDURE USP_SEL_DOCUMENTO_DATA(
    PI_ID_CONVOCATORIA NUMBER,
    PI_ID_CRITERIO NUMBER,
    PI_ID_CASO NUMBER,
    PI_ID_DOCUMENTO NUMBER,
    PI_ID_INSCRIPCION NUMBER,
    PO_REF OUT SYS_REFCURSOR
  )AS
  BEGIN
    OPEN PO_REF FOR
    SELECT  *
    FROM    T_GEND_CONV_CRI_CASO_DOC_INSC
    WHERE   ID_CRITERIO = PI_ID_CRITERIO 
            AND ID_CASO = PI_ID_CASO
            AND ID_CONVOCATORIA = PI_ID_CONVOCATORIA
            AND ID_DOCUMENTO = PI_ID_DOCUMENTO
            AND ID_INSCRIPCION = PI_ID_INSCRIPCION
            AND FLAG_ESTADO = '1';
  END USP_SEL_DOCUMENTO_DATA;
  
  PROCEDURE USP_PRC_CONV_CRI_CAS_INSC_DATA(
    PI_ID_CONVOCATORIA NUMBER,
    PI_ID_CRITERIO NUMBER,
    PI_ID_CASO NUMBER,
    PI_ID_INSCRIPCION NUMBER,
    PI_USUARIO_GUARDAR NUMBER,
    PO_ROWAFFECTED OUT NUMBER
  )IS
        vCONT NUMBER;
  BEGIN
    SELECT COUNT(*) INTO vCONT 
    FROM T_GEND_CONV_CRI_CASO_INSC_DATA
    WHERE ID_CRITERIO = PI_ID_CRITERIO 
          AND ID_CASO = PI_ID_CASO
          AND ID_CONVOCATORIA = PI_ID_CONVOCATORIA
          AND ID_INSCRIPCION = PI_ID_INSCRIPCION;
          
    IF vCONT = 0 THEN 
      INSERT INTO T_GEND_CONV_CRI_CASO_INSC_DATA (ID_CONVOCATORIA, ID_CRITERIO, ID_CASO, ID_INSCRIPCION, INGRESO_DATOS, REG_USUARIO, REG_FECHA)
      VALUES (PI_ID_CONVOCATORIA, PI_ID_CRITERIO, PI_ID_CASO, PI_ID_INSCRIPCION, '1',PI_USUARIO_GUARDAR, SYSDATE);
    ELSE
      UPDATE T_GEND_CONV_CRI_CASO_INSC_DATA
      SET    INGRESO_DATOS = '1',
             UPD_USUARIO = PI_USUARIO_GUARDAR,
             UPD_FECHA = SYSDATE
      WHERE  ID_CRITERIO = PI_ID_CRITERIO 
             AND ID_CASO = PI_ID_CASO
             AND ID_CONVOCATORIA = PI_ID_CONVOCATORIA
             AND ID_INSCRIPCION = PI_ID_INSCRIPCION;
    END IF;
    PO_ROWAFFECTED := SQL%ROWCOUNT;      
  END USP_PRC_CONV_CRI_CAS_INSC_DATA;
  
  PROCEDURE USP_SEL_VERF_CONV_CRITERIO_INSC(
    PI_ID_CONVOCATORIA NUMBER,
    PI_ID_CRITERIO NUMBER,
    PI_ID_INSCRIPCION NUMBER,
    PO_REF OUT SYS_REFCURSOR
  )AS
  BEGIN
    OPEN PO_REF FOR
    SELECT
    C.ID_CASO,
    C.NOMBRE,
    C.ID_CRITERIO,
    C.FLAG_ESTADO
    FROM    T_GEND_CONV_CRI_CASO_INSC_DATA CCID LEFT JOIN
    T_GENM_CASO C ON CCID.ID_CASO = C.ID_CASO AND CCID.ID_CRITERIO = C.ID_CRITERIO 
    WHERE   CCID.ID_CRITERIO = PI_ID_CRITERIO 
            AND CCID.ID_CONVOCATORIA = PI_ID_CONVOCATORIA
            AND CCID.ID_INSCRIPCION = PI_ID_INSCRIPCION
            AND CCID.FLAG_ESTADO = '1';
  END USP_SEL_VERF_CONV_CRITERIO_INSC;
END PKG_SRES_CRITERIO;

/
