create or replace PACKAGE PKG_SRES_ADMIN AS 

  PROCEDURE USP_SEL_USUARIO(
        PO  OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_SEL_USUARIO_CORREO(
        pCORREO  IN VARCHAR2,
        pCURSOR  OUT SYS_REFCURSOR
  );

END PKG_SRES_ADMIN;