------------------------------------------------------------------------------------------
CREATE SEQUENCE SRES.SQ_MAE_SECTOR MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 3 INCREMENT BY 1;
CREATE SEQUENCE SRES.SQ_GENM_INSTITUCION MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 2 INCREMENT BY 1;
CREATE SEQUENCE SRES.SQ_GENM_USUARIO MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 2 INCREMENT BY 1;
CREATE SEQUENCE SRES.SQ_GENM_CRITERIO MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 9 INCREMENT BY 1;

-------------------------------------------------------------------------------------------------------------------
CREATE TABLE T_MAE_SECTOR(
ID_SECTOR NUMBER,
NOMBRE VARCHAR2(50),
FLAG_ESTADO VARCHAR2(1) DEFAULT '1',
REG_USUARIO NUMBER,
REG_FECHA DATE DEFAULT SYSDATE,
UDP_USUARIO NUMBER,
UPD_FECHA DATE,
CONSTRAINT SECTOR_PK PRIMARY KEY(ID_SECTOR)
);

CREATE TABLE  T_GENM_INSTITUCION(
ID_INSTITUCION NUMBER,
RUC NUMBER(11,0),
RAZON_SOCIAL VARCHAR2(100),
DOMICILIO_LEGAL VARCHAR2(120),
ID_SECTOR NUMBER,
FLAG_ESTADO VARCHAR2(1) DEFAULT '1',
REG_USUARIO NUMBER,
REG_FECHA DATE DEFAULT SYSDATE,
UDP_USUARIO NUMBER,
UPD_FECHA DATE,
CONSTRAINT INSTITUCION_PK PRIMARY KEY(ID_INSTITUCION),
CONSTRAINT SECTOR_FK FOREIGN KEY (ID_SECTOR) REFERENCES T_MAE_SECTOR(ID_SECTOR)
);

CREATE TABLE T_MAE_ROL(
ID_ROL NUMBER,
NOMBRE VARCHAR(50),
FLAG_ESTADO VARCHAR2(1) DEFAULT '1',
REG_USUARIO NUMBER,
REG_FECHA DATE DEFAULT SYSDATE,
UDP_USUARIO NUMBER,
UPD_FECHA DATE,
CONSTRAINT ROL_PK PRIMARY KEY (ID_ROL)
);

CREATE TABLE T_GENM_USUARIO (
ID_USUARIO NUMBER,
NOMBRES VARCHAR2(30),
APELLIDOS VARCHAR2(50),
CORREO VARCHAR2(100),
CONTRASENA VARCHAR2(100),
TELEFONO VARCHAR2(10),
ANEXO VARCHAR2(6),
CELULAR VARCHAR2(12),
ID_INSTITUCION NUMBER,
ID_ROL NUMBER,
FLAG_ESTADO VARCHAR2(1) DEFAULT '1',
REG_USUARIO NUMBER,
REG_FECHA DATE DEFAULT SYSDATE,
UDP_USUARIO NUMBER,
UPD_FECHA DATE,
CONSTRAINT USUARIO_PK PRIMARY KEY (ID_USUARIO),
CONSTRAINT INSTITUCION_FK FOREIGN KEY (ID_INSTITUCION) REFERENCES T_GENM_INSTITUCION (ID_INSTITUCION),
CONSTRAINT ROL_FK FOREIGN KEY (ID_ROL) REFERENCES T_MAE_ROL (ID_ROL)
);

CREATE TABLE T_GENM_CRITERIO(
ID_CRITERIO NUMBER,
NOMBRE VARCHAR2(100),
FLAG_ESTADO VARCHAR2(1) DEFAULT '1',
REG_USUARIO NUMBER,
REG_FECHA DATE DEFAULT SYSDATE,
UDP_USUARIO NUMBER,
UPD_FECHA DATE,
CONSTRAINT CRITERIO_PK PRIMARY KEY (ID_CRITERIO)
);




------------------------------------------
--T_MAE_SECTOR
INSERT INTO T_MAE_SECTOR (ID_SECTOR, NOMBRE, REG_USUARIO) VALUES (1, 'SECTOR PÚBLICO', 1);
INSERT INTO T_MAE_SECTOR (ID_SECTOR, NOMBRE, REG_USUARIO) VALUES (2, 'SECTOR PRIVADO', 1);

--T_GENM_INSTITUCION
INSERT INTO T_GENM_INSTITUCION (ID_INSTITUCION, RUC, RAZON_SOCIAL, DOMICILIO_LEGAL, ID_SECTOR, REG_USUARIO) 
VALUES (1, '20103040501', 'Minesterio de Energía y Minas', 'Av Javier Prado 724', 1, 1);

--T_MAE_ROL
INSERT INTO T_MAE_ROL (ID_ROL, NOMBRE, REG_USUARIO) VALUES (1, 'ADMINISTRADOR', 0);
INSERT INTO T_MAE_ROL (ID_ROL, NOMBRE, REG_USUARIO) VALUES (2, 'EVALUADOR', 1);
INSERT INTO T_MAE_ROL (ID_ROL, NOMBRE, REG_USUARIO) VALUES (3, 'POSTULANTE', 1);

--T_GENM_USUARIO
INSERT INTO T_GENM_USUARIO (ID_USUARIO, NOMBRES, APELLIDOS, CORREO, CONTRASENA, TELEFONO, ANEXO, CELULAR, ID_INSTITUCION, ID_ROL, REG_USUARIO)
VALUES (1, 'Carlos', 'Galdos', 'carlos@grupo-zuniga.com', 'AK6/N7RQH5kHaUb1RDlVFzBkupiWnfger8B3053UodvdNnMdZqCWYcQs17U2i9Cujw==', '3785212', '1010', '925478365', 1, 1, 1);

--T_GENM_CRITERIO
INSERT INTO T_GENM_CRITERIO (ID_CRITERIO, NOMBRE) VALUES (1, 'Criterio 1');
INSERT INTO T_GENM_CRITERIO (ID_CRITERIO, NOMBRE) VALUES (2, 'Criterio 2');
INSERT INTO T_GENM_CRITERIO (ID_CRITERIO, NOMBRE) VALUES (3, 'Criterio 3');
INSERT INTO T_GENM_CRITERIO (ID_CRITERIO, NOMBRE) VALUES (4, 'Criterio 4');
INSERT INTO T_GENM_CRITERIO (ID_CRITERIO, NOMBRE) VALUES (5, 'Criterio 5');
INSERT INTO T_GENM_CRITERIO (ID_CRITERIO, NOMBRE) VALUES (6, 'Criterio 6');
INSERT INTO T_GENM_CRITERIO (ID_CRITERIO, NOMBRE) VALUES (7, 'Criterio 7');
INSERT INTO T_GENM_CRITERIO (ID_CRITERIO, NOMBRE) VALUES (8, 'Criterio 8');
-----------------------------------------
DROP TABLE T_MAE_SECTOR;
DROP TABLE T_GENM_INSTITUCION;
DROP TABLE T_MAE_ROL;
DROP TABLE T_GENM_USUARIO;
DROP TABLE T_GENM_CRITERIO;


--------------------------
SELECT * FROM T_MAE_SECTOR;
SELECT * FROM T_GENM_INSTITUCION;
SELECT * FROM T_MAE_ROL;
SELECT * FROM T_GENM_USUARIO;
SELECT * FROM T_GENM_CRITERIO;